import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css';
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes';
import Header1 from './Header1'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
  
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Theme appearance="light" accentColor="teal" grayColor="sage" radius="full" scaling="90%">
        <Header1 />
        <main>{children}</main>
        </Theme>
        </body>
    </html>
  )
}
